### PR TITLE
Microverse JS_Library Project

### PR DESCRIPTION
**Pull request by gurbuzertunga**
In this project we;

- Created an online book library,
- Library has two hard coded books,
- User can create new books and choose if he/she read these,
- User can then update their book reading status,
- Books are stored in an array called myLibrary.

### CODE REVIEW

**Review by mikenath223 — CHANGES_REQUESTED** [review]
### Hello Team 👋

**You both have done well on this. Good work. 👍**

- [x] Currently, the contents of your library aren't easy to read please remove the dark overlapping modal.

- [x] Is there a reason for package.lock.json in your project files. Please remove it.

- [x] OPTIONAL - Consider adding form validation to prevent creating an empty book.

- [x] OPTIONAL - Also you can persist the book array in localStorage.
 
### **STATUS: CHANGES REQUESTED** 👷‍♂️

Kindly fix these issues and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

HAPPY CODING👨‍💻

**Comment by gurbuzertunga** [comment]
Note: package-lock.json is present because it uses Babel to conpile ES6 to ES5 for the classes we used. local storage is added to project now.

**Review by rOluochKe — CHANGES_REQUESTED** [review]
Hello Team
### You have done well so far :clap: However, you have an issue to fix:-
- [x] Follow the git-flow guideline, make the development branch main, and create feature branches from the development branch. Main is to only be used during production.
### Make the changes and submit for another code review. Good luck.
- Happy coding!

**Review by rOluochKe — APPROVED** [review]
### You got it right :clap: The project has been approved. Congratulations :boom: :100:
### Merge and submit the project. Good luck with the next one.
- Happy coding!

**Pull request merged**
